project:
  type: website

website:
  title: "Zain Munir"
  navbar:
    left:
      - href: projects/index.qmd
        text: Projects
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: "https://github.com/ZainMunir/zainmunir.github.io"
        title: "Source Code"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto